const OK_CODE = 200;
const CREATED_CODE = 201;
const BAD_REQ_ERROR_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  OK_CODE,
  CREATED_CODE,
  BAD_REQ_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  DEFAULT_ERROR_CODE,
};
